### ISSUE TITLE
Empty value with following comment

### ISSUE THREAD

**Issue by davalv** [benhoyt/inih#55]
Hi there!
Currently the library doesn't support an empty value with a following comment.
For example:

`A_KEY = ;This is a comment`

Is it possible to support this possibility?

Thank you!

**Comment by benhoyt** [comment]
Hi @davalv thanks for the report. Yeah, this was a definite bug with how I was skipping whitespace before looking for the comment (and the comment needs to be prefixed with whitespace, so it thought it wasn't a comment). Fixed in https://github.com/benhoyt/inih/commit/dbf771afeb58fe569908dd9b0048585eef78c422 -- thanks for the report.
