### ISSUE TITLE
Array of items

### ISSUE THREAD

**Issue by imtrobin** [benhoyt/inih#60]
Hi, is it able to support array of items, like this

[list_of_files]
item.txt
item1.txt
item2.txt

**Comment by benhoyt** [comment]
It is possible, but not as you've shown (that will return "error on line 2", because you need `key=value` pairs). However, you can do it using multi-line syntax, where each subsequent line is indented:

```
[list_of_files]
files = item.txt
        item1.txt
        item2.txt
```

If you're using the straight C version of inih, that will call your handler three times, with `files` as the key each time, and you can create the array yourself. If you're using the C++ `INIReader` wrapper, it'll return the files in a single newline-separated string.

If you don't like the whitespace indentation, you can manually specify `files =` on each line, which should be exactly the same as the above:

```
[list_of_files]
files = item.txt
files = item1.txt
files = item2.txt
```
