### ISSUE TITLE
Text on line after section doesn't trigger an error

### ISSUE THREAD

**Issue by jamespharvey20** [benhoyt/inih#82]
It looks like Python ConfigParser behaves the same way, so you might close this saying it's desired behavior to stay compatible with it.  But, you did deviate allowing key/value pairs outside of a section (glad you did), so I wanted to point this issue out in case you wanted to deviate here too.

EDIT: Maybe if it's desired behavior, there could be an option for whether to error.

I was surprised this:

    [section] this really shouldn't be here
    key=value

Doesn't trigger an error on the ` this really shouldn't be here`, since it's not a comment.  As it is, it has a section `section` with a key `key` and a value `value`.  Anything on a line after a section just seems to go away.  I'd rather it trigger an error.

I'll also note this:

    [section] # comment

Currently works as a comment, since anything on the line after the section appears to be ignored.  If you change it to raise an error if there's anything else there, it would be worth deciding whether to allow a `#` comment here still, or treat that as an error.  (This makes no difference to me.)

**Comment by benhoyt** [comment]
Hi @jamespharvey20, thanks for the report. I've played with this a bit, and don't think it's worth fixing. Partly because it's consistent with Python's `ConfigParser` as you point out, but partly also because it shouldn't cause issues for any real INI files and it's not (quite) backwards-compatible, so would require adding yet another `#define` option to enable this "strict section" mode. So I'd rather leave this as is.
